# Exercise 2

In [1]:
from thinkdsp import Signal, Sinusoid, SquareSignal, TriangleSignal, SawtoothSignal, ParabolicSignal
from thinkdsp import normalize, unbias, PI2, decorate
from thinkdsp import Chirp
from thinkdsp import read_wave
from thinkdsp import Spectrum, Wave, UncorrelatedGaussianNoise, Spectrogram
from thinkdsp import Noise

import numpy as np
import pandas as pd

from matplotlib import pyplot

import thinkstats2

from scipy.stats import linregress

import scipy
import scipy.fftpack

loglog = dict(xscale='log', yscale='log')

PI2 = np.pi * 2

In [5]:
y = [-0.5, 0.1, 0.7, -0.1]
np.fft.fft(y)

array([ 0.2+0.j , -1.2-0.2j,  0.2+0.j , -1.2+0.2j])

In [6]:
def dft(ys):
    N = len(ys)
    ts = np.arange(N) / N
    freqs = np.arange(N)
    args = np.outer(ts, freqs)
    M = np.exp(1j * PI2 * args)
    amps = M.conj().transpose().dot(ys)
    return amps

dft(y)

array([ 0.2+0.00000000e+00j, -1.2-2.00000000e-01j,  0.2+1.95943488e-16j,
       -1.2+2.00000000e-01j])

In [11]:
def fft(y):
    N = len(y)
    half = N // 2
    
    if half == 0:
        return y
    
    e = np.zeros((half))
    o = np.zeros((half))
    
    for it in range(half):
        e[it] = y[it * 2]
        o[it] = y[it * 2 + 1]
        
    # len() may be less than half
    # (if half is odd)
    dft_e = fft(e)
    dft_o = fft(o)
    M = len(dft_e)
    
    dft_e_tiled = np.tile(dft_e, 2)
    dft_o_tiled = np.tile(dft_o, 2)
    
    dft = np.zeros((M * 2), dtype=np.complex)
    
    for it in range(M * 2):
        dft[it] = dft_e_tiled[it] + np.exp(-PI2 * 1j * it / (M*2)) * dft_o_tiled[it]
        
    return dft

fft(y)

array([ 0.2+0.j , -1.2-0.2j,  0.2+0.j , -1.2+0.2j])